server:
  port: 8080
  servlet:
    context-path: /store

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: toor

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "b2yoP+BXkNpTkT3UA7TSAHxqoLxuzgZIRmscynx2zbm5PHbtt3U+JB5N1G6AIrNg"
  valid-duration: 3600
  refreshable-duration: 7200

pagination:
  default-page-size: 4

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: OPEYU6E4
    secretKey: GYIOOG67IRBGS6GA1C4Q9VTOICRG1LDP
    returnUrl: http://localhost:8080/store/api/payment/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other
